"use client";

import React from "react";

import { Button } from "@/components/ui/button";

import { useParams } from "next/navigation";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { Page, Text, View, Document, StyleSheet, PDFDownloadLink } from "@react-pdf/renderer";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils/currency.utils";
import { TripsV1ById } from "@/lib/types/types";
import { BRAND_NAME } from "@/lib/config/brand";

const pdfStyles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: "#fff",
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  title: {
    fontSize: 18,
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "bold",
  },
  row: {
    flexDirection: "row",
    marginBottom: 8,
  },
  label: {
    fontWeight: "bold",
    width: 120,
  },
  value: {
    flex: 1,
  },
  footer: {
    marginTop: 30,
    fontSize: 10,
    textAlign: "center",
    color: "#555",
  },
});

// PDF Component
function TripPDF({ data }: Readonly<{ data: TripsV1ById }>) {
  const renderData = data?.data;
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>Trip Report</Text>

        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Date:</Text>
          <Text style={pdfStyles.value}>
            {renderData?.date ? new Date(renderData.date).toLocaleDateString() : "N/A"}
          </Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Trip ID:</Text>
          <Text style={pdfStyles.value}>{renderData?.tripId ?? "-"}</Text>
        </View>

        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Company:</Text>
          <Text style={pdfStyles.value}>{renderData?.companyName ?? "-"}</Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Route:</Text>
          <Text style={pdfStyles.value}>{renderData?.routeName ?? "-"}</Text>
        </View>

        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Lane:</Text>
          <Text style={pdfStyles.value}>{renderData?.routeTypeName ?? "-"}</Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Type:</Text>
          <Text style={pdfStyles.value}>{renderData?.tripTypeName ?? "-"}</Text>
        </View>

        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Driver:</Text>
          <Text style={pdfStyles.value}>{renderData?.driverName ?? "-"}</Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Vehicle:</Text>
          <Text style={pdfStyles.value}>{renderData?.vehicleName ?? "-"}</Text>
        </View>

        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Touch Point:</Text>
          <Text style={pdfStyles.value}>{renderData?.touchPoint ?? "-"}</Text>
        </View>

        <Text style={pdfStyles.footer}>
          Generated by {BRAND_NAME} — {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
}

// Page Component
export default function TripsViewById() {
  const params = useParams();
  const id = params?.id;

  const tripData = useQuery(
    api.trip_v1.getTripV1,
    id
      ? {
          id: id as Id<"trip_v1">,
        }
      : "skip",
  );

  if (!tripData?.success) {
    return <div>Trip not found</div>;
  }

  const data = tripData.data;

  return (
    <Card className="max-w-2xl mt-8">
      <CardHeader>
        <CardTitle>Trip Information</CardTitle>
      </CardHeader>
      <CardContent className="prose max-w-none">
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div>
            <span className="font-semibold text-gray-600">Date:</span>{" "}
            {data?.date ? new Date(data.date).toLocaleDateString() : "N/A"}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Company:</span> {data?.companyName}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Lane:</span> {data?.routeTypeName}
          </div>
          <div>
            <span className="font-semibold text-gray-600">type:</span> {data?.tripTypeName}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Touch Point:</span> {data?.touchPoint}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Route:</span> {data?.routeName}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Driver:</span> {data?.driverName}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Vehicle:</span> {data?.vehicleName}
          </div>
          <div>
            <span className="font-semibold text-gray-600">Cost:</span>
            {formatCurrency(data?.cost, "INR")}
          </div>
        </div>

        <div className="mt-6">
          <PDFDownloadLink document={<TripPDF data={tripData} />} fileName="trip-details.pdf">
            {({ loading }) => (
              <Button variant="default" className="gap-2 cursor-pointer">
                {loading ? "Preparing PDF..." : "⬇ Download Trip Report"}
              </Button>
            )}
          </PDFDownloadLink>
        </div>
      </CardContent>
    </Card>
  );
}
