// Generates dist/index.js with all webp images embedded as base64 data URIs.
// This makes the published package fully self-contained (no asset file loading needed).
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const assetsDir = join(root, 'assets');
const distDir = join(root, 'dist');

const iconNames = readdirSync(assetsDir)
  .filter((f) => f.endsWith('.webp'))
  .sort();

// name -> base64 data URI
const catalog = {};
for (const file of iconNames) {
  const name = file.replace(/\.webp$/i, '');
  const data = readFileSync(join(assetsDir, file));
  catalog[name] = `data:image/webp;base64,${data.toString('base64')}`;
}

const names = Object.keys(catalog)
  .map((n) => JSON.stringify(n))
  .join(', ');

const src = `// Generated by scripts/build.js. Do not edit.
const ICONS = ${JSON.stringify(catalog, null, 2)};

// Array of available icon names, e.g. ['1', '2', '5'].
export const iconNames = ${JSON.stringify(Object.keys(catalog))};

// Return the data URI (src) for an icon by name.
export function iconSrc(name) {
  if (!(name in ICONS)) throw new Error(\`webp-icons: unknown icon "\${name}". Available: \${Object.keys(ICONS).join(', ')}\`);
  return ICONS[name];
}

// Return a ready-to-use <img> HTML string for an icon.
// options: { size, alt, className }
export function renderIcon(name, options = {}) {
  const { size, alt = name, className = '' } = options;
  const dim = size ? \`width:\${size}px;height:\${size}px\` : '';
  const style = dim ? \` style="\${dim};object-fit:contain"\` : '';
  const cls = className ? \` class="\${className}"\` : '';
  return \`<img src="\${iconSrc(name)}" alt="\${alt}"\${cls}\${style}/>\`;
}

export default ICONS;
`;

mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'index.js'), src, 'utf8');
writeFileSync(join(distDir, 'index.mjs'), src, 'utf8');
console.log(`Built ${Object.keys(catalog).length} icons:`, Object.keys(catalog).join(', '));