import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";

const fontDMSans = DM_Mono({
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${fontDMSans.className} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
